name: Build and Upload .deb Artifact

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like "v1.0.0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential xclip dpkg-dev gh

      - name: Build .deb package
        run: |
          VERSION="${GITHUB_REF##*/}"
          chmod +x build_deb.sh
          VERSION=${VERSION#v} ./build_deb.sh

      - name: Create GitHub Release if not exists
        run: |
          VERSION="${GITHUB_REF##*/}"
          gh release view "$VERSION" || gh release create "$VERSION" --title "$VERSION" --notes "Automated release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .deb to Existing Release
        run: |
          VERSION="${GITHUB_REF##*/}"
          gh release upload "$VERSION" "hcp_*.deb" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
