name: Build and Upload .deb Artifact

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like "v1.0.0"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential xclip dpkg-dev

      - name: Build .deb package
        run: |
          VERSION="${GITHUB_REF##*/}"
          cd hcp
          chmod +x build_deb.sh
          VERSION=${VERSION#v} ./build_deb.sh
          mv hcp_*.deb ../

      - name: Upload .deb as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: hcp-deb
          path: hcp_*.deb 