name: Build and Upload .deb Artifact

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like "v1.0.0"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev

      - name: Build in Ubuntu 20.04 Docker container
        run: |
          VERSION=${GITHUB_REF##*/}
          VERSION=${VERSION#v}
          docker run --rm -v $PWD:/src -w /src ubuntu:20.04 bash -c "
            apt-get update &&
            apt-get install -y build-essential xclip dpkg-dev &&
            VERSION=$VERSION ./build_deb.sh
          "

      - name: Create GitHub Release if not exists
        run: |
          VERSION="${GITHUB_REF##*/}"
          gh release view "$VERSION" || gh release create "$VERSION" --title "$VERSION" --notes "Automated release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .deb to Existing Release
        run: |
          VERSION="${GITHUB_REF##*/}"
          gh release upload "$VERSION" "hcp_*.deb" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
