name: Test hcp .deb

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Check code formatting
        run: |
          find src include -name '*.cpp' -o -name '*.hpp' | xargs clang-format --dry-run --Werror

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libx11-6 dpkg xvfb xclip

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build latest .deb
        run: |
          chmod +x build_deb.sh
          ./build_deb.sh

      - name: Install hcp .deb
        run: |
          sudo dpkg -i hcp_*.deb
          sudo apt-get install -f -y

      - name: Make test script executable
        run: chmod +x test_hcp.sh

      - name: Run hcp E2E test
        run: xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' ./test_hcp.sh 

      - name: Build all tests with Makefile
        run: |
          cd test
          make clean
          make

      - name: Run tray app Unit test
        run: ./test/test_trey_app

      - name: Run db/clipboard Unit test
        run: ./test/test_db_clipboard 
